In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense

# each example (of which we have a 100) is a sequence of 10 words and
# each words is encoded as 16 element vectors

X = np.random.rand(100, 10, 16) 
y = np.random.choice(2, 100)

Using TensorFlow backend.


In [2]:
y

array([1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1])

In [64]:
X[0]

array([[0.16012356, 0.37944803, 0.84754721, 0.11950098, 0.88617542,
        0.5274501 , 0.18919931, 0.93192969, 0.1295937 , 0.28699136,
        0.5344727 , 0.54129973, 0.58132998, 0.71956285, 0.97054108,
        0.71241856],
       [0.63683563, 0.74666887, 0.096432  , 0.8267742 , 0.64133161,
        0.16616679, 0.35699533, 0.391651  , 0.39236485, 0.21043898,
        0.43624268, 0.77557576, 0.16529743, 0.2955633 , 0.1860017 ,
        0.70619548],
       [0.50971618, 0.12726424, 0.84913792, 0.73266793, 0.07215063,
        0.87272524, 0.10890824, 0.86798195, 0.53320838, 0.93803785,
        0.11904051, 0.88628298, 0.8096362 , 0.54732045, 0.64360992,
        0.53109316],
       [0.21177344, 0.42537887, 0.64345055, 0.27568344, 0.56553937,
        0.91292452, 0.90523184, 0.03454677, 0.11608827, 0.70358814,
        0.56905739, 0.48474321, 0.57104675, 0.84116043, 0.02682524,
        0.20579723],
       [0.70829757, 0.29573045, 0.72394293, 0.80088861, 0.66480302,
        0.31857513, 0.53155121, 

In [21]:
from keras.utils import np_utils
Y = np_utils.to_categorical(y,2)

In [65]:
Y

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.

In [58]:
model = Sequential()

In [59]:
model.add(LSTM(128, input_shape = (10,16)))

In [60]:
model.add(Dense(2, activation="softmax"))

In [61]:
model.compile(loss = "categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [62]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_7 (LSTM)                (None, 128)               74240     
_________________________________________________________________
dense_9 (Dense)              (None, 2)                 258       
Total params: 74,498
Trainable params: 74,498
Non-trainable params: 0
_________________________________________________________________


In [63]:
# fit model
model.fit(X, Y, epochs=10, batch_size=8)

Epoch 1/10
100/100 [==============================] - 2s 18ms/step - loss: 0.7051 - acc: 0.4600
Epoch 2/10
100/100 [==============================] - 0s 5ms/step - loss: 0.6921 - acc: 0.5300

In [56]:
data = np.array([
[0.1, 1.0],
[0.2, 0.9],
[0.3, 0.8],
[0.4, 0.7],
[0.5, 0.6],
[0.6, 0.5],
[0.7, 0.4],
[0.8, 0.3],
[0.9, 0.2],
[1.0, 0.1]])

In [57]:
data.shape

(10, 2)